# Generated by Django 6.0.6 on 2026-06-21 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_origen', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('retirado', 'Retirado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foto_entrega_url', models.URLField(blank=True)),
                ('firma_digital', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='clientes.cliente')),
                ('id_repartidor', models.ForeignKey(blank=True, db_column='id_repartidor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='repartidores.repartidor')),
            ],
            options={
                'db_table': 'envio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
