# Generated by Django 6.0.6 on 2026-06-21 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('calificacion_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'repartidor',
            },
        ),
    ]
