# Generated by Django 6.0.6 on 2026-06-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repartidores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartidor',
            name='calificacion_avg',
        ),
    ]
