# Generated by Django 6.0.6 on 2026-06-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('origenGeo', models.CharField(max_length=255)),
                ('destinoGeo', models.CharField(max_length=255)),
                ('distanciaKm', models.FloatField()),
                ('pesoKg', models.FloatField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('retirado', 'Retirado'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('precio', models.FloatField()),
                ('fotoEntrega', models.ImageField(blank=True, null=True, upload_to='entregas/')),
                ('firmaDigital', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='usuarios.cliente')),
                ('id_repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='usuarios.repartidor')),
            ],
        ),
    ]
