# Generated by Django 6.0.6 on 2026-06-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('repartidor', 'Repartidor')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'proxy': False,
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('calificacion', models.FloatField(default=0.0)),
            ],
            bases=('usuarios.usuario',),
        ),
    ]
