# Generated by Django 6.0.6 on 2026-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_envio_lat_destino_envio_lat_origen_envio_lng_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_estado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
